[package]
name = "tracks-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[[bin]]
name = "tracks-window"
path = "src/main.rs"


[dependencies]
glam = { version = "0.29", features = [
    "core-simd",
] } #SIMD supported vector types


# window library for plotting
minifb = { version = "0.28", optional = true }
plotters = { version = "0.3", optional = true }

# for reading and writing files
serde_json = { version = "1.0", optional = true }

[features]
plot = ["dep:minifb", "dep:plotters"]
json = ["dep:serde_json"]
default = ["plot", "json"]
