[package]
name = "tracks-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[[bin]]
name = "tracks-window"
path = "src/main.rs"


[dependencies]
glam = { version = "0.30", features = [
    "core-simd",
] } #SIMD supported vector types\
palette = "0.7.6"

# for reading and writing files
serde_json = { version = "1.0", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
minifb = { version = "0.28", optional = true }
plotters = { version = "0.3", optional = true }

[build-dependencies]
cbindgen = "0.28"

[features]
plot = ["dep:minifb", "dep:plotters"]
json = ["dep:serde_json"]
default = ["json", "plot"]
